global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'themis-framework'
    environment: 'production'

scrape_configs:
  # Themis API metrics
  - job_name: 'themis-api'
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'themis-orchestrator'
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
