name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Restore virtualenv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'requirements*.txt', 'setup.cfg', 'setup.py') }}

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install -e .[dev]

      - name: Update PATH
        run: echo "$(pwd)/.venv/bin" >> $GITHUB_PATH

      - name: Install project in editable mode when cached
        if: steps.cache-venv.outputs.cache-hit == 'true'
        run: pip install -e .[dev]

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: QA checks
        run: make qa

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            **/*.log
            outputs/**
          if-no-files-found: ignore
